CREATE OR REPLACE PROCEDURE "USP_POPULATE_PROMO_DIMENSION"()
RETURNS VARCHAR(100)
LANGUAGE SQL
EXECUTE AS OWNER
AS '
BEGIN 

    INSERT INTO RPT."DIM PROMO"(
        MESSAGEID,
        "Promo Group",
        ID
    )
    
    WITH ALL_MESSAGEID AS (
        SELECT DISTINCT
            TIM.MESSAGEID
        FROM CDP.PUBLIC.TRANSACTIONSUMMARY T
        LEFT JOIN CDP.PUBLIC.TRANSACTIONITEMMESSAGEXREF AS TIM ON T.SOURCETRANSACTIONITEMNUMBER = TIM.SOURCETRANSACTIONITEMNUMBER
        LEFT JOIN CDP.PUBLIC.CUSTOMERSUMMARY CS ON T.MASTERCUSTOMERID = CS.MASTERCUSTOMERID
        LEFT JOIN CDP.PUBLIC.TIMESUMMARY TS ON DATE(T.TRANSACTIONDATE) = DATE(TS.DATEINUNIX)
        WHERE TO_DATE(T.TRANSACTIONTIMESTAMP) >= (
            SELECT TO_DATE(DATEINUNIX) 
            FROM EDW_MARKETING_PRD.ANALYTICS.TIMESUMMARY 
            WHERE FISCALYEAR = (
                SELECT FISCALYEAR 
                FROM CDP.PUBLIC.TIMESUMMARY 
                WHERE TO_DATE(DATEINUNIX) > CURRENT_DATE - 7 
                    AND TO_DATE(DATEINUNIX) <= CURRENT_DATE 
                    AND FISCALDAYOFWEEK = 7
            ) - 2 
            AND FISCALDAYOFMONTH = 1 
            AND FISCALMONTH = 1
        )
        -- AND TO_DATE(T.TRANSACTIONTIMESTAMP) <= (
        --     SELECT MAX(TS.DATEINUNIX::DATE) 
        --     FROM CDP.PUBLIC.TIMESUMMARY TS
        --     WHERE TS.DATEINUNIX::DATE <= CURRENT_DATE::DATE
        --     AND TS.FISCALDAYOFWEEK = 7
        -- )
        AND T.SUBTYPE IN (''Demand'', ''Shipped'') 
        AND BUYERIDENTIFICATION = ''Identified''

        UNION

        SELECT DISTINCT
            TIM.MESSAGEID
        FROM DS_DEV.PUBLIC.TRANSACTIONSUMMARY_MW_20240308 T
        LEFT JOIN CDP.PUBLIC.TRANSACTIONITEMMESSAGEXREF AS TIM ON T.SOURCETRANSACTIONITEMNUMBER = TIM.SOURCETRANSACTIONITEMNUMBER
        LEFT JOIN CDP.PUBLIC.CUSTOMERSUMMARY CS ON T.MASTERCUSTOMERID = CS.MASTERCUSTOMERID
        LEFT JOIN CDP.PUBLIC.TIMESUMMARY TS ON DATE(T.TRANSACTIONDATE) = DATE(TS.DATEINUNIX)
        WHERE TS.FISCALYEAR = 2023
        AND T.SUBTYPE IN (''Demand'', ''Shipped'') 
        AND BUYERIDENTIFICATION = ''Identified''

        UNION 

        SELECT DISTINCT
            TIM.MESSAGEID
        FROM CDP_JC.PUBLIC.TRANSACTIONSUMMARY T
        LEFT JOIN CDP_JC.PUBLIC.TRANSACTIONITEMMESSAGEXREF AS TIM ON T.SOURCETRANSACTIONITEMNUMBER = TIM.SOURCETRANSACTIONITEMNUMBER
        LEFT JOIN CDP_JC.PUBLIC.CUSTOMERSUMMARY CS ON T.MASTERCUSTOMERID = CS.MASTERCUSTOMERID
        LEFT JOIN CDP.PUBLIC.TIMESUMMARY TS ON DATE(T.TRANSACTIONDATE) = DATE(TS.DATEINUNIX)
        WHERE TO_DATE(T.TRANSACTIONTIMESTAMP) >= (
            SELECT TO_DATE(DATEINUNIX) 
            FROM EDW_MARKETING_PRD.ANALYTICS.TIMESUMMARY 
            WHERE FISCALYEAR = (
                SELECT FISCALYEAR 
                FROM CDP.PUBLIC.TIMESUMMARY 
                WHERE TO_DATE(DATEINUNIX) > CURRENT_DATE - 7 
                    AND TO_DATE(DATEINUNIX) <= CURRENT_DATE 
                    AND FISCALDAYOFWEEK = 7
            ) - 2 
            AND FISCALDAYOFMONTH = 1 
            AND FISCALMONTH = 1
        )
        -- AND TO_DATE(T.TRANSACTIONTIMESTAMP) <= (
        --     SELECT MAX(TS.DATEINUNIX::DATE) 
        --     FROM CDP.PUBLIC.TIMESUMMARY TS
        --     WHERE TS.DATEINUNIX::DATE <= CURRENT_DATE::DATE
        --     AND TS.FISCALDAYOFWEEK = 7
        -- )
        AND T.SUBTYPE IN (''Demand'', ''Shipped'') 
        AND BUYERIDENTIFICATION = ''Identified''

        UNION

        SELECT DISTINCT
            TIM.MESSAGEID
        FROM DS_DEV.PUBLIC.TRANSACTIONSUMMARY_JC_20240308 T
        LEFT JOIN CDP_JC.PUBLIC.TRANSACTIONITEMMESSAGEXREF AS TIM ON T.SOURCETRANSACTIONITEMNUMBER = TIM.SOURCETRANSACTIONITEMNUMBER
        LEFT JOIN CDP_JC.PUBLIC.CUSTOMERSUMMARY CS ON T.MASTERCUSTOMERID = CS.MASTERCUSTOMERID
        LEFT JOIN CDP_JC.PUBLIC.TIMESUMMARY TS ON DATE(T.TRANSACTIONDATE) = DATE(TS.DATEINUNIX)
        WHERE TS.FISCALYEAR = 2023
        AND T.SUBTYPE IN (''Demand'', ''Shipped'') 
        AND BUYERIDENTIFICATION = ''Identified''
    ),
    TRANSFORMED_DATA AS (
        SELECT DISTINCT
            MESSAGEID,
            CASE
                WHEN REGEXP_COUNT(MESSAGEID, ''-'') = 1 THEN SPLIT_PART(MESSAGEID, ''-'', 1)
                ELSE MESSAGEID
            END AS "Promo Group"
        FROM ALL_MESSAGEID
    ),

    GET_NEW_RECORDS AS (
        SELECT 
        MESSAGEID,
        "Promo Group"
        FROM
        TRANSFORMED_DATA

        EXCEPT

        SELECT 
        MESSAGEID,
        "Promo Group"
        FROM
        RPT."DIM PROMO"
    ),

    GET_MAX_ID AS (
        SELECT COALESCE(MAX("ID"), 0) AS MAX_ID
        FROM
        RPT."DIM PROMO"
    )

    SELECT
        MESSAGEID,
        "Promo Group",
        RANK() OVER(ORDER BY MESSAGEID) + (SELECT MAX_ID FROM GET_MAX_ID) AS ID
    FROM GET_NEW_RECORDS;

    -- Return success message
    RETURN ''Table RPT."DIM PROMO" created or replaced successfully.'';

END
';