CREATE OR REPLACE PROCEDURE "USP_POPULATE_GA_CHANNEL"()
RETURNS VARCHAR(100)
LANGUAGE SQL
EXECUTE AS OWNER
AS '
BEGIN 

INSERT INTO RPT."GA CHANNEL"(
    "Source",
    "Channel",
    "Channel Type",
    "Channel Sub Type",
    "Initiative",
    "Source Initiative",
    C_CAMPAIGN,
    ID
)

WITH ALL_CHANNEL AS
(
    SELECT 
    DISTINCT
    C_DEVICETYPE,
    C_LASTTOUCHCHANNEL,
    C_SOURCE,
    C_INITIATIVE,
    C_CAMPAIGN,
    TS.ID
    FROM
    CDP.PUBLIC.TRANSACTIONSUMMARY T
    LEFT JOIN CDP.PUBLIC.CUSTOMERSUMMARY CS ON T.MASTERCUSTOMERID = CS.MASTERCUSTOMERID
    LEFT JOIN CDP.PUBLIC.TIMESUMMARY TS ON DATE(T.TRANSACTIONDATE) = DATE(TS.DATEINUNIX)
    WHERE
    TO_DATE(T.TRANSACTIONTIMESTAMP) >= (
        SELECT TO_DATE(DATEINUNIX) 
        FROM CDP.PUBLIC.TIMESUMMARY 
        WHERE FISCALYEAR = (
            SELECT FISCALYEAR 
            FROM CDP.PUBLIC.TIMESUMMARY 
            WHERE TO_DATE(DATEINUNIX) > CURRENT_DATE - 7 
                AND TO_DATE(DATEINUNIX) <= CURRENT_DATE 
                AND FISCALDAYOFWEEK = 7
        ) - 2 
        AND FISCALDAYOFMONTH = 1 
        AND FISCALMONTH = 1
    )
    AND TO_DATE(T.TRANSACTIONTIMESTAMP) <= (
        SELECT MAX(TS.DATEINUNIX::DATE) 
        FROM CDP.PUBLIC.TIMESUMMARY TS
        WHERE TS.DATEINUNIX::DATE <= CURRENT_DATE::DATE
        AND TS.FISCALDAYOFWEEK = 7
    )
    AND T.SUBTYPE IN (''Demand'', ''Shipped'') 
    AND BUYERIDENTIFICATION = ''Identified''

    UNION

    SELECT 
    DISTINCT
    C_DEVICETYPE,
    C_LASTTOUCHCHANNEL,
    C_SOURCE,
    C_INITIATIVE,
    C_CAMPAIGN,
    TS.ID
    FROM
    DS_DEV.PUBLIC.TRANSACTIONSUMMARY_MW_20240308 T
    LEFT JOIN CDP.PUBLIC.CUSTOMERSUMMARY CS ON T.MASTERCUSTOMERID = CS.MASTERCUSTOMERID
    LEFT JOIN CDP.PUBLIC.TIMESUMMARY TS ON DATE(T.TRANSACTIONDATE) = DATE(TS.DATEINUNIX)
    WHERE TS.FISCALYEAR = 2023
    AND T.SUBTYPE IN (''Demand'', ''Shipped'') 
    AND BUYERIDENTIFICATION = ''Identified''

    UNION 

    SELECT 
    DISTINCT
    C_DEVICETYPE,
    C_LASTTOUCHCHANNEL,
    C_SOURCE,
    C_INITIATIVE,
    C_CAMPAIGN,
    TS.ID
    FROM
    CDP_JC.PUBLIC.TRANSACTIONSUMMARY T
    LEFT JOIN CDP_JC.PUBLIC.CUSTOMERSUMMARY CS ON T.MASTERCUSTOMERID = CS.MASTERCUSTOMERID
    LEFT JOIN CDP.PUBLIC.TIMESUMMARY TS ON DATE(T.TRANSACTIONDATE) = DATE(TS.DATEINUNIX)
    WHERE
    TO_DATE(T.TRANSACTIONTIMESTAMP) >= (
        SELECT TO_DATE(DATEINUNIX) 
        FROM CDP.PUBLIC.TIMESUMMARY 
        WHERE FISCALYEAR = (
            SELECT FISCALYEAR 
            FROM CDP.PUBLIC.TIMESUMMARY 
            WHERE TO_DATE(DATEINUNIX) > CURRENT_DATE - 7 
                AND TO_DATE(DATEINUNIX) <= CURRENT_DATE 
                AND FISCALDAYOFWEEK = 7
        ) - 2 
        AND FISCALDAYOFMONTH = 1 
        AND FISCALMONTH = 1
    )
    AND TO_DATE(T.TRANSACTIONTIMESTAMP) <= (
        SELECT MAX(TS.DATEINUNIX::DATE) 
        FROM CDP.PUBLIC.TIMESUMMARY TS
        WHERE TS.DATEINUNIX::DATE <= CURRENT_DATE::DATE
        AND TS.FISCALDAYOFWEEK = 7
    )
    AND T.SUBTYPE IN (''Demand'', ''Shipped'') 
    AND BUYERIDENTIFICATION = ''Identified''

    UNION

    SELECT 
    DISTINCT
    C_DEVICETYPE,
    C_LASTTOUCHCHANNEL,
    C_SOURCE,
    C_INITIATIVE,
    C_CAMPAIGN,
    TS.ID
    FROM
    DS_DEV.PUBLIC.TRANSACTIONSUMMARY_JC_20240308 T
    LEFT JOIN CDP_JC.PUBLIC.CUSTOMERSUMMARY CS ON T.MASTERCUSTOMERID = CS.MASTERCUSTOMERID
    LEFT JOIN CDP_JC.PUBLIC.TIMESUMMARY TS ON DATE(T.TRANSACTIONDATE) = DATE(TS.DATEINUNIX)
    WHERE TS.FISCALYEAR = 2023
    AND T.SUBTYPE IN (''Demand'', ''Shipped'') 
    AND BUYERIDENTIFICATION = ''Identified''
    
),

TRANSFORMED_DATA AS
(
    SELECT
        DISTINCT
        coalesce(C_SOURCE, '''') AS "Source",
    CASE
        WHEN TS.ID < ''20230528''
        AND C_LASTTOUCHCHANNEL IN (''EMAIL'') THEN ''EMAIL''
        WHEN TS.ID < ''20230528''
        AND C_LASTTOUCHCHANNEL IN (''SMS'') THEN ''SMS''
        WHEN TS.ID < ''20230528''
        AND C_LASTTOUCHCHANNEL IN (''DISPLAY'') THEN ''DISPLAY''
        WHEN TS.ID < ''20230528''
        AND C_LASTTOUCHCHANNEL IN (''PAID SEARCH'') THEN ''PAID SEARCH''
        WHEN TS.ID < ''20230528''
        AND C_LASTTOUCHCHANNEL IN (''SOCIAL'') THEN ''SOCIAL''
    
        WHEN TS.ID >= ''20230528''
            AND CONTAINS (C_INITIATIVE,
                ''YOUTUBE''
        ) THEN ''DISPLAY''
    
        WHEN TS.ID >= ''20230528''
            AND C_LASTTOUCHCHANNEL IN (
                ''CPC'',
                ''PAID_SEARCH'',
                ''(UNLINKED SA360 ACCOUNT)'',
                ''PAID SEARCH''
        ) THEN ''PAID SEARCH''
    
        WHEN C_CAMPAIGN IN (''AFFI0001'',''MWAFFI00001'') THEN ''AFFILIATE''
        WHEN C_SOURCE in (''AFFILIATE'') THEN ''AFFILIATE''
        WHEN C_LASTTOUCHCHANNEL IN (''AFFILIATE'', ''AFFILIATES'') THEN ''AFFILIATE''
    
        WHEN C_CAMPAIGN=''PASSWORD-RESET-EMAIL'' THEN ''REFERRAL''
        WHEN C_CAMPAIGN=''2024_JC_WEBAPPPASSWORDLESSLOGIN_US_EMSL'' THEN ''REFERRAL''
        WHEN C_SOURCE IN (''TALKABLE'') THEN ''REFERRAL''
    
        WHEN TS.ID >= ''20230528''
            AND C_LASTTOUCHCHANNEL IN (''EMAIL'', ''EMAILL'') THEN ''EMAIL''
        WHEN TS.ID >= ''20230528''
            AND C_LASTTOUCHCHANNEL IN (''SMS'', ''TEXT'') THEN ''SMS''
        WHEN TS.ID >= ''20230528'' AND C_CAMPAIGN IN (''SMS_OPTIN'') THEN ''SMS''
        WHEN TS.ID >= ''20230528''
            AND C_SOURCE IN (''ATTENTIVE'') THEN ''SMS''
        WHEN TS.ID >= ''20230528''
            AND C_LASTTOUCHCHANNEL IN (''DISPLAY'', ''VIDEO'') THEN ''DISPLAY''
        WHEN TS.ID >= ''20230528''
            AND C_SOURCE IN (''DBM'') THEN ''DISPLAY''
        WHEN TS.ID >= ''20230528''
            AND C_LASTTOUCHCHANNEL IN (''SOCIAL'', ''PARTNERSHIP'', ''PAID'') THEN ''SOCIAL''
        WHEN TS.ID >= ''20230528''
            AND C_SOURCE IN (''PINTEREST'',''REDDIT'',''SNAPCHAT'',''YOUTUBE'',''FACEBOOK'',''INSTAGRAM'',''TIKTOK'',''MESSENGER'',''DHGALLERIES'',''DASHHUDSON'',''DASH HUDSON'') THEN ''SOCIAL''
    
        WHEN TS.ID >= ''20230528''
        AND (
            (
                C_SOURCE = ''(DIRECT)''
                AND C_LASTTOUCHCHANNEL IN (''(NOT SET)'', ''(NONE)'')
            )
        ) THEN ''DIRECT''
        WHEN C_DEVICETYPE = ''APP'' THEN ''APP''
        WHEN C_LASTTOUCHCHANNEL IN (
            ''NATURAL SEARCH'',
            ''ORGANIC SEARCH'',
            ''ORGANIC'',
            ''SEO''
        ) THEN ''SEO''
        WHEN C_LASTTOUCHCHANNEL = ''REFERRAL'' AND
            (
                C_SOURCE ILIKE ''%YOUTUBE%''
                OR C_SOURCE ILIKE ''%FACEBOOK%''
                OR C_SOURCE ILIKE ''%PINTEREST%''
                OR C_SOURCE ILIKE ''%REDDIT%''
                OR C_SOURCE ILIKE ''%INSTAGRAM%''
                OR C_SOURCE ILIKE ''%SNAPCHAT%''
            ) THEN ''SOCIAL''
        WHEN C_LASTTOUCHCHANNEL = ''SHARE'' THEN ''REFERRAL''
        WHEN C_LASTTOUCHCHANNEL = ''REFERRAL'' AND
        (
            C_SOURCE NOT ILIKE ''%YOUTUBE%''
            AND C_SOURCE NOT ILIKE ''%FACEBOOK%''
            AND C_SOURCE NOT ILIKE ''%PINTEREST%''
            AND C_SOURCE NOT ILIKE ''%REDDIT%''
            AND C_SOURCE NOT ILIKE ''%INSTAGRAM%''
            AND C_SOURCE NOT ILIKE ''%SNAPCHAT%''
        )
        THEN ''REFERRAL''
        WHEN C_SOURCE IN (''NARVAR'', ''SHEERID_SHOPPERS'', ''STOREQRCODE'',''THREDUP'',''BRANCH'',''ASSOCIATE'') THEN ''REFERRAL''
        WHEN C_LASTTOUCHCHANNEL IN (''MBL DTS'', ''WEB DTS'', ''DIRECT'') THEN ''DIRECT''
        WHEN C_LASTTOUCHCHANNEL IN (''APP DTS'') THEN ''APP''
        WHEN C_LASTTOUCHCHANNEL IN (
            ''INTERNAL'',
            ''OTHER'',
            ''(OTHER)'',
            ''MISC'',
            ''OC NOT CAPTURED''
        ) THEN ''OC NOT CAPTURED''
        WHEN C_LASTTOUCHCHANNEL IN (''CUSTOMER SERVICE CHANNEL'') THEN ''CUSTOMER SERVICE CHANNEL''
        ELSE ''OTHER''
        END AS "Channel",
        CASE
            WHEN "Channel" IN (
                ''EMAIL'',
                ''SMS'',
                ''DIRECT'',
                ''REFERRAL'',
                ''SEO'',
                ''APP'',
                ''CUSTOMER SERVICE CHANNEL'',
                ''OC NOT CAPTURED'',
                ''ORGANIC SEARCH''
            ) THEN ''FREE''
            WHEN "Channel" IN (''AFFILIATE'', ''PAID SEARCH'', ''SOCIAL'', ''DISPLAY'') THEN ''PAID''
            ELSE ''FREE''
        END AS "Channel Type",
        CASE
            WHEN "Channel" IN (''EMAIL'', ''SMS'') THEN ''EMAIL + SMS''
            WHEN "Channel" IN (''DIRECT'', ''REFERRAL'', ''ORGANIC SEARCH'', ''SEO'') THEN ''ORGANIC CHANNELS''
            WHEN "Channel" IN (''CUSTOMER SERVICE CHANNEL'', ''OC NOT CAPTURED'') THEN ''OTHER''
            ELSE "Channel"
        END AS "Channel Sub Type",
        CASE 
        WHEN "Channel" = ''SEO'' THEN ''Other''
        WHEN "Channel" = ''OTHER'' THEN ''Other''
        WHEN "Channel" = ''UNASSIGNED'' THEN ''Other''
        WHEN "Channel" = ''OC NOT CAPTURED'' THEN ''Other''
        WHEN "Channel" = ''DISPLAY'' THEN ''Other''
        WHEN "Channel" = ''DIRECT'' THEN ''Other''
        WHEN "Channel" = ''APP'' THEN ''Other''
        WHEN "Channel" = ''CUSTOMER SERVICE CHANNEL'' THEN ''Other''
        
        WHEN "Channel" = ''EMAIL'' AND C_CAMPAIGN  IN (''RETURNCONFIRMATION_CONTACTUS'',''MW_ORDER_SHIPPED'',''MW_INVENTORY_CANCEL'',''MW_CUSTOMERCANCEL'',''MW_STORE_PICKUP'',''EGC'',''MW_THREDUP_EGC'',''MW_EGC'',''REVIEW_APPROVED'',''20211207_JC_FTC_CANCEL'',''PIE'',''20211207_JC_ACCESS_POINT_PICKUP'',''20211207_JC_FTC_DELAY'',''20211207_JC_WAITLIST_CANCEL'',''20211207_JC_ORDER_DELIVERED'',''MW_BROWSE_PDP_W2_LOYALTY_OCT2017'') THEN ''Transactional''
        
        WHEN "Channel" = ''EMAIL'' AND C_CAMPAIGN IN 
        (''BLUECORE_W_ABANDONSEARCH_MWEMBR06812'',''BLUECORE_W_BACKINSTOCK_FAVORITES_MWEMBR07131'',''BLUECORE_W_LOWINVENTORY_MWEMBR06808'',''BLUECORE_M_ABANDONBROWSE_T2_MWEMBR06807'',''BLUECORE_W_ABANDONBROWSE_T2_MWEMBR06806'',''BLUECORE_W_ABANDONBROWSE_MWEMBR06804'',''BLUECORE_M_ABANDONCART_ T2_MWEMBR06803'',''BLUECORE_W_ABANDONCART_T2_MWEMBR06802'',''BLUECORE_M_ABANDONCART_MWEMBR06801'',''BLUECORE_W_ABANDONCART_MWEMBR06800'',''BLUECORE_M_PRICEDECREASE_SALE_MWEMBR06888'',''BLUECORE_POSTPURCHASE_MWEMBR03695'',''BLUECORE_W_ABANDONCART_CATCHUP_MWEMBR06798'',''BLUECORE_W_POSTPURCHASE_DENIM_T2_MWEMBR07262'',''BLUECORE_W_PRICEDECREASE_SALE_MWEMBR06887'',''BLUECORE_W_SMARTCAMPAIGN_MONDAY_MWEMBR06891'',''BLUECORE_W_SMARTCAMPAIGN_SATURDAY_MWEMBR06889'',''BLUECORE_W_BACKINSTOCK_MWEMBR06810'',''MWEMBR06691-LOYALTY_HALFBIRTHDAY'',''MWEMBR02876-MERKLE_LOYALTY_HALFBIRTHDAY_REMINDER'',''MWEMBR02875-MERKLE_LOYALTY_BIRTHDAY_REMINDER'',''MWEMBR03643-LOYALTY_BIRTHDAY'',''MWEMBR04283-LOYALTYPOINTS_REWARDEARNED'',''MWEMBR04284-LOYALTYPOINTS_REWARDEXPIRINGSOON'',''MWEMBR04285-LOYALTYPOINTS_CLOSETOREWARD'',''MWEMBR05602-MW_WELCOME_DYNAMIC_T1_STOREPOS'',''MWEMBR05608-MW_WELCOME_DYNAMIC_T3'',''MWEMBR06503-LOYALTYPOINTS_REWARD1DAYEXPIRATION'',''MWEMBR05601-MW_WELCOME_DYNAMIC_T1_INSIDERWEB'',''MWEMBR07191-20230721_DUAL_ANNIVERSARYOFFER_50PTS'',''MWEMBR07192-20230721_DUAL_ANNIVERSARYOFFER_2XPTS'',''OW_EM_TR_MC_NI_NI_202309_321789_ABANDON_CART_NON_INCENTIVE_EMAILA_BOOMERANG_RTM_US'',''OW_EM_TR_MC_NI_NI_202309_321789_ABANDON_CART_NON_INCENTIVE_EMAILB_BOOMERANG_RTM_US'' )THEN ''Trigger''
        
        WHEN "Channel" = ''EMAIL'' AND C_CAMPAIGN IN (''MWEMBR06645-20230210_DUAL_REEBOKEXCLUSIVEDROP'',''MWEMBR05697-20220123_W_ACTIVEROUNDUP'',''MWEMBR06055-20220603_ICONTOTE'',''MWEMBR06300-20220923_LOYALTYMIGRATION_REMINDER'',''MWEMBR06326-20221004_50DENIMACTIVATION'',''MWEMBR06606-20230124_W_SPRINGDENIMLAUNCH_V1'',''MWEMBR06607-20230124_W_SPRINGDENIMLAUNCH_V2'',''MWEMBR06623-20230201_MAKERSIGHTS_DENIM'',''MWEMBR06658-20230216_W_INFLUENCERROUNDUP_V1'',''MWEMBR06659-20230216_W_INFLUENCERROUNDUP_V2'',''MWEMBR06824-20230328_MAKERSIGHTS_KNITS'',''MWEMBR06825-20230328_MAKERSIGHTS_SHIRTS'',''MWEMBR06838-20230330_MAKERSIGHTS_ACTIVE'',''MWEMBR07086-20230624_W_FLASHSALEPROMO_LAUNCH_ME'',''MWEMBR07210-20230726_DUAL_MYSTERYOFFER_HIDDEN'',''MWEMBR07277-20230815_W_AUG2NARO'',''MWEMBR07288-20230819_W_REGENCHINOCAPSULE_V1'',''MWEMBR07289-20230819_W_REGENCHINOCAPSULE_V2'',''MWEMBR07364-20230908_W_NIMBLE_WANTNOWWEARNOW'' ,''MWEMBR07449-20231004_W_SWEATERSHOP'' ,''MWEMBR07500-20231025_W_NOVNARO'',''MWEMBR07507-20231028_W_SWEATERSHOP'',''MWEMBR07508-20231029_W_NEWARRIVALSREPULSE'',''MWEMBR07540-20231110_DUAL_NOVEOYCOMMS_INSIDERS'',''MWEMBR07553-20231115_W_WANTLISTEDIT2'',''MWEMBR07571-20231125_W_NOKIDHUNGRY'',''MWEMBR06604-20230202_DUAL_REFERAFRIEND'',''MWEMBR06615-20230128_W_RELAXEDTAILORINGBLAZERS'',''MWEMBR06621-20230201_W_KICKOUTDENIM'',''MWEMBR06624-20230202_W_DENIMONDENIM'',''MWEMBR06627-20230204_W_TRENDSUITING'') THEN ''Branding''
        
        WHEN "Channel" = ''EMAIL'' AND C_CAMPAIGN  IN (''MWEMBR07583-20231127_M_CYBERMONDAY'',''MWEMBR06238-20220901_DUAL_LOYALTY10GIFT'',''MWEMBR07417-20230923_W_LOYALTYPROMO_R4_ME'',''MWEMBR07452-20231005_W_IPDPROMO_LAUNCH'',''MWEMBR07471-20231013_W_40OFFSALE25OFFTOPS_LAUNCH'',''MWEMBR07477-20231015_W_40OFFSALE25OFFTOPS_R1'',''MWEMBR07481-20231017_W_40OFFSALE25OFFTOPS_R2'',''MWEMBR07494-20231022_W_40OFFSALE25OFFTOPS_R4'',''MWEMBR07496-20231024_W_40OFFSALE25OFFTOPS_R5'',''MWEMBR07520-20231102_W_JACKETSBOOTSPROMO_LAUNCH'',''MWEMBR07525-20231104_W_JACKETSBOOTSPROMO_R1'',''MWEMBR07528-20231105_W_JACKETSBOOTSPROMO_R1_ME'',''MWEMBR07535-20231109_W_BLACKFRIDAYLAUNCH'',''MWEMBR07546-20231112_W_DRESSEDUPEASYSHINE_V1'',''MWEMBR07547-20231112_W_DRESSEDUPEASYSHINE_V2'',''MWEMBR07548-20231113_W_BLACKFRIDAY_R1'',''MWEMBR07549-20231111_W_BLACKFRIDAYLAUNCH_ME'',''MWEMBR07552-20231115_W_NEWARRIVALSREPULSE'',''MWEMBR07554-20231116_W_BLACKFRIDAY_R2'',''MWEMBR07558-20231117_DUAL_LOYALTYINSTOREEA'',''MWEMBR07560-20231118_W_BLACKFRIDAY_R3'',''MWEMBR07561-20231118_M_BLACKFRIDAY_R2'',''MWEMBR07563-20231121_W_50OFFTONSOFSALE'',''MWEMBR07566-20231121_W_BLACKFRIDAY_R4'',''MWEMBR07567-20231121_M_BLACKFRIDAY_R3'',''MWEMBR07572-20231123_W_BLACKFRIDAY_R5'',''MWEMBR07573-20231123_M_BLACKFRIDAY_R4'',''MWEMBR07574-20231124_W_BLACKFRIDAY_R6'',''MWEMBR07575-20231124_M_BLACKFRIDAY_R5'',''MWEMBR07577-20231124_W_BLACKFRIDAY_R7'',''MWEMBR07577-20231124_W_BLACKFRIDAY_R7'',''MWEMBR07578-20231124_W_BLACKFRIDAY_R8'',''MWEMBR07579-20231125_W_BLACKFRIDAY_R9'',''MWEMBR07580-20231126_W_BLACKFRIDAY_R10'',''MWEMBR07581-20231126_W_CYBERMONDAY'',''MWEMBR07582-20231127_W_CYBERMONDAY_R1'',''MWEMBR07583-20231127_M_CYBERMONDAY'',''MWEMBR07584-20231127_W_CYBERMONDAY_R2'',''MWEMBR07585-20231127_W_CYBERMONDAY_R3'',''MWEMBR07591-20231127_M_CYBERMONDAY_R1'') THEN ''Promo''
        
        WHEN "Channel" = ''EMAIL'' AND C_CAMPAIGN IN (''MMWEMBR07559-20231117_W_SATINHARLOWINTRO_EAAUDIENCE'',''MWEMBR05950-20220420_W_OFFEREXPIRATIONTEST_90DAYS'',''MWEMBR06512-20221210_W_BESTOFBESTSWEATERS_V1'',''MWEMBR06516-20221210_W_BESTOFBESTSWEATERS_V2'',''MWEMBR06523-20221214_W_PARTYDRESSING_V1'',''MWEMBR06524-20221214_W_PARTYDRESSING_V2'',''MWEMBR06549-20221229_W_WINTERWHITES_V1'',''MWEMBR06550-20221229_W_WINTERWHITES_V2'',''MWEMBR06576-20230110_W_RESOLUTIONREVOLUTION_V1'',''MWEMBR06577-20230110_W_RESOLUTIONREVOLUTION_V2'',''MWEMBR06581-20230112_W_BASICSREFRESH_V1'' ,''MWEMBR06582-20230112_W_BASICSREFRESH_V2'' ,''MWEMBR06591-20230117_W_RESOLUTIONREVOLUTION_V1'',''MWEMBR06592-20230117_W_RESOLUTIONREVOLUTION_V2'',''MWEMBR07241-20230807_W_CREATIVECHOICE_DRESSES_ME'',''MWEMBR07330-20230829_W_FALLCOLLECTION_LAUNCH'',''MWEMBR07483-20231018_W_ITALIANWOOLCAPSULE'',''MWEMBR07485-20231019_W_SWEATERSTEXTUREFOCUS'',''MWEMBR07491-20231021_W_3RDPARTYFOOTWEAR'',''MWEMBR07523-20231103_W_GIFTGUIDELAUNCH'',''MWEMBR07531-20231107_W_WANTLISTSPOTLIGHTBAGS'',''MWEMBR07534-20231108_W_CREATIVECHOICE_HOLIDAYOUTFITTING'',''MWEMBR07544-20231112_W_WANTLISTREPULSE'',''MWEMBR07538-20231110_W_MILLEDINITALY'',''MWEMBR07550-20231114_W_WINTERCOLLECTION'',''MWEMBR07562-20231119_W_HOLIDAYDRESSING'',''MWEMBR07564-20231120_W_WINTERCAPSULEWARDROBE'',''MWEMBR07568-20231121_W_NEWINDENIM'',''MWEMBR07569-20231122_W_WANTLISTINVESTMENTPIECES'',''MWEMBR07570-20231122_M_OUTERWEARSHOP'') THEN ''Mix''
        
        WHEN "Channel" = ''EMAIL'' AND STARTSWITH(C_CAMPAIGN,''ORDER-'') THEN ''Transactional''
        
        WHEN "Channel" = ''EMAIL'' AND C_CAMPAIGN = ''WELCOME'' AND C_SOURCE=''BLUECORE'' THEN ''Trigger''
        
        WHEN "Channel" = ''EMAIL'' AND C_CAMPAIGN=''WELCOME_1_MW_OCT2017'' AND C_SOURCE=''EMAIL'' THEN ''Trigger''
        
        WHEN "Channel" = ''EMAIL'' AND C_CAMPAIGN=''MW_BROWSE_PDP_W2_LOYALTY_OCT2017'' AND C_SOURCE=''EMAIL'' THEN ''Trigger''
        
        WHEN "Channel" = ''SMS'' AND CONTAINS(C_SOURCE,''ATTENTIVE'') AND CONTAINS(C_CAMPAIGN,''SPRINGCOLLECTION'') THEN ''Marketing''
        WHEN "Channel" = ''SMS'' AND CONTAINS(C_SOURCE,''ATTENTIVE'') AND CONTAINS(C_CAMPAIGN,''(NOT SET)'') THEN ''Marketing''
        WHEN "Channel" = ''SMS'' AND CONTAINS(C_SOURCE,''ATTENTIVE'') AND CONTAINS(C_CAMPAIGN,''25OFF150'') THEN ''Promo''
        WHEN "Channel" = ''SMS'' AND CONTAINS(C_SOURCE,''ATTENTIVE'') AND CONTAINS(C_CAMPAIGN,''25OFF150'') THEN ''Promo''
        WHEN "Channel" = ''SMS'' AND CONTAINS(C_SOURCE,''ATTENTIVE'') AND CONTAINS(C_CAMPAIGN,''20220331_UPTO40OFF_LAUNCH'') THEN ''Promo''
        WHEN "Channel" = ''SMS'' AND C_CAMPAIGN  IN (''MSMS00002-20220406_MW_WELCOME1'',''MSMS00003-20220406_MW_WELCOME2'',''MSMS00108-20221214_MW_LOYALTY_REWARDEXPIRING'',''MSMS00124-20230104_MW_LOYALTY_BIRTHDAY'',''MSMS00125-20230104_MW_LOYALTY_BIRTHDAYREMINDER'',''MSMS00128-20230104_MW_LOYALTY_CLOSETOUPGRADE_STAR'',''SMS-EGIFTCARD122321'') THEN ''Trigger''
        WHEN "Channel" = ''SMS'' AND REGEXP_LIKE(C_CAMPAIGN,''MSMS00378-20230928_MW_W_OCTOBER1NA'') AND REGEXP_LIKE(C_SOURCE,''^SFMC$'', ''i'') THEN ''Marketing''
        WHEN "Channel" = ''SMS'' AND C_CAMPAIGN  IN (''MSMS00413-20231116_MW_W_BLACKFRIDAY40OFF'',''MSMS00416-20231121_MW_W_BLACKFRIDAY_NEWSTYLESADDED'',''MSMS00417-20231124_MW_W_BLACKFRIDAY_50OFF'',''MSMS00419-20231126_MW_W_CYBERMONDAY'') THEN ''Promo''
        
        WHEN "Channel" = ''SOCIAL'' AND CONTAINS(C_CAMPAIGN,''ADVANTAGEPLUS'') THEN ''Advantage Plus''
        WHEN "Channel" = ''SOCIAL'' AND CONTAINS(C_CAMPAIGN,''DABA'') THEN ''Dynamic''
        WHEN "Channel" = ''SOCIAL'' AND CONTAINS(C_CAMPAIGN,''DPA'') THEN ''Dynamic''
        
        WHEN C_CAMPAIGN IN (''BR^US^WHENTHEFITHITS^AUG^AP^TRAFF^F^8.23.2022AP^AP^ENG_WCA_CRM^PPLA^DENIM^WOMENSBRANDCAMPAIGN_PAIDCAROUSELGRID'') THEN ''Product''
        
        WHEN "Channel" = ''SOCIAL'' AND C_CAMPAIGN  IN (''PR^US^ADVANTAGEPLUS^NOV^AP^CONV^F^11.09.2023^AP^AP^DEMO^PPLA^TOPS^BLACKFRIDAYPROMO_30OFF_GREENSWEATER'',''PR^US^ADVANTAGEPLUS^NOV^AP^CONV^F^11.09.2023^AP^AP^DEMO^PPVA^MULTI^BLACKFRIDAYPROMO_30OFF_WANTLIST'',''PR^US^ADVANTAGEPLUS^NOV^AP^CONV^F^11.16.2023^AP^AP^DEMO^PPLA^GRAPHIC^BLACKFRIDAYPROMO_40OFF_BERRIES'',''PR^US^ADVANTAGEPLUS^NOV^AP^CONV^F^11.16.2023^AP^AP^DEMO^PPLA^TOPS^BLACKFRIDAYPROMO_40OFF_WHITESWEATER'',''PR^US^ADVANTAGEPLUS^NOV^AP^CONV^F^11.23.2023^AP^AP^DEMO^PPLA^DENIM^BLACKFRIDAYPROMO_50OFF_DENIM'',''PR^US^ADVANTAGEPLUS^NOV^AP^CONV^F^11.23.2023^AP^AP^DEMO^PPLA^GRAPHIC^BLACKFRIDAYPROMO_50OFF_BERRIES'',''PR^US^ADVANTAGEPLUS^NOV^AP^CONV^F^11.23.2023^AP^AP^DEMO^PPLA^GRAPHIC^BLACKFRIDAYPROMO_50OFF_GRAPHIC'',''PR^US^ADVANTAGEPLUS^NOV^AP^CONV^F^11.23.2023^AP^AP^DEMO^PPLA^MULTI^BLACKFRIDAYPROMO_50OFF_DUALGENDER'',''PR^US^ADVANTAGEPLUS^NOV^AP^CONV^F^11.23.2023^AP^AP^DEMO^PPLA^PANTS^BLACKFRIDAYPROMO_50OFF_HARLOWPANT'',''PR^US^ADVANTAGEPLUS^NOV^AP^CONV^F^11.23.2023^AP^AP^DEMO^PPLA^TOPS^BLACKFRIDAYPROMO_50OFF_WHITESWEATER'',''PR^US^ADVANTAGEPLUS^NOV^AP^CONV^F^11.26.2023^AP^AP^DEMO^PPLA^DENIM^BLACKFRIDAYPROMO_CYBERMONDAY_DENIM'',''PR^US^ADVANTAGEPLUS^NOV^AP^CONV^F^11.26.2023^AP^AP^DEMO^PPLA^GRAPHIC^BLACKFRIDAYPROMO_CYBERMONDAY_GRAPHIC'',''PR^US^ADVANTAGEPLUS^NOV^AP^DPA^F^11.16.2023^AP^AP^DEMO^MPPA^BLACKFRIDAYPROMOCOPY_40OFF^NOCR'',''PR^US^ADVANTAGEPLUS^NOV^AP^DPA^F^11.23.2023^AP^AP^DEMO^MPPA^BLACKFRIDAYPROMOCOPY_50OFF^NOCR'',''PR^US^ADVANTAGEPLUS^NOV^AP^DPA^F^11.26.2023^AP^AP^DEMO^MPPA^BLACKFRIDAYPROMOCOPY_CYBERMONDAY^NOCR'',''PR^US^ADVANTAGEPLUS^SEPT^AP^CONV^F^9.12.2023^AP^AP^DEMO^PPLA^DENIM^HARLOW_LOYALTYPROMO'') THEN ''Promo''
        
        WHEN "Channel" = ''SOCIAL'' AND CONTAINS(C_SOURCE,''TIKTOK'') AND CONTAINS(C_CAMPAIGN,''CREATOR'') THEN ''Creator''
        WHEN "Channel" = ''SOCIAL'' AND CONTAINS(C_SOURCE,''FACEBOOK'') AND CONTAINS(C_CAMPAIGN,''PRODUCT_LDWPROMO'') THEN ''Promo''
        WHEN "Channel" = ''SOCIAL'' AND CONTAINS(C_SOURCE,''FACEBOOK'') AND CONTAINS(C_CAMPAIGN,''PROMO_EXTRA30OFFSALE'') THEN ''Promo''
        WHEN "Channel" = ''SOCIAL'' AND CONTAINS(C_SOURCE,''^(?I)FACEBOOK$'') AND CONTAINS(C_CAMPAIGN,''PRODUCT'') THEN ''Product''
        WHEN "Channel" = ''SOCIAL'' AND CONTAINS(C_SOURCE, ''PINTEREST'') AND CONTAINS(C_CAMPAIGN,''PAID'') THEN ''Product''
        WHEN "Channel" = ''SOCIAL'' AND CONTAINS(C_SOURCE, ''PINTEREST'') AND CONTAINS(C_CAMPAIGN,''PINTEREST'') THEN ''Organic''
        WHEN "Channel" = ''SOCIAL'' AND CONTAINS(C_SOURCE, ''DHGALLERIES'') AND CONTAINS(C_CAMPAIGN,''SITE'') THEN ''Organic''
        WHEN "Channel" = ''SOCIAL'' AND CONTAINS(C_SOURCE, ''DASHHUDSON'') THEN ''Organic''
        WHEN "Channel" = ''SOCIAL'' AND CONTAINS(C_SOURCE, ''IGSHOPPING'') THEN ''Organic''
        WHEN "Channel" = ''SOCIAL'' AND REGEXP_LIKE(C_SOURCE,''TIKTOK'') AND CONTAINS(C_CAMPAIGN,''OBJECTIVETEST_'') THEN ''Product''
        WHEN "Channel" = ''SOCIAL'' AND REGEXP_LIKE(C_SOURCE, ''TIKTOK'') AND REGEXP_LIKE(C_INITIATIVE,''CONTENT'') THEN ''Product''
        WHEN "Channel" = ''SOCIAL'' AND C_SOURCE IN (''HOOBE'',''XOMACENNA'') THEN ''Creator''
        WHEN "Channel" = ''SOCIAL'' AND CONTAINS(C_CAMPAIGN,''RT^US^PROMO_EXTRA30OFF^DEC^FAN_FB_IG^CONV^F^12_26_2020^DE_MO^EXIG_FEFB_FEIG_MPFB_NBIAN_STFB_STIG^CRM_WCA^PPLA^PROMO_EXTRA30OFF_2^12_26_BIGDEAL_30OFFSALE_PAIDINFEED_3_12_26_BIGDEAL'') THEN ''Promo''
        WHEN "Channel" = ''SOCIAL'' AND CONTAINS(C_CAMPAIGN,''RT^US^PRODUCT^OCT^FAN_FB_IG^CONV^F^10_06_2020^DE_MO^EXIG_FEFB_FEIG_NBIAN^CRM_WCA^PPLA^NEWARRIVALS^OCTOBERCROPS14_RTED'') THEN ''Product''
        WHEN "Channel" = ''SOCIAL'' AND CONTAINS(C_CAMPAIGN,''OSMINST901'') OR CONTAINS(C_CAMPAIGN,''MWPINT0247'') THEN ''Organic''
        WHEN "Channel" = ''SOCIAL'' AND C_CAMPAIGN  IN (''OSMINST-99105940549'',''LIKESHOP'',''LATER-LINKINBIO-CREATIVEGROWTH'') THEN ''Organic''
        WHEN "Channel" = ''SOCIAL'' AND CONTAINS(C_CAMPAIGN,''RT-USNOVEMBERNEWARRIVALS10.24|NO|US|NF}|D|FB|PPLA|F|38|47|NOLIST|NOINT|NOBHV|CRMMWLOYAL'') THEN ''Product''
        WHEN "Channel" = ''SOCIAL'' AND CONTAINS(C_CAMPAIGN,''RT^US^PROMO_UPTO40OFF^APR^FAN_FB_IG^CONV^F^04_06_2021^DE_MO^EXIG_FEFB_FEIG_MPFB_NBIAN_STIG^CRM_WCA^PPLA^UPTO40OFF^04_06_UPTO40OFFPURCHASE_PAIDINFEED-6'') THEN ''Promo''
        WHEN "Channel" = ''SOCIAL'' AND REGEXP_LIKE(C_SOURCE,''^DASH HUDSON$'', ''i'') THEN ''Organic''
        WHEN "Channel" = ''SOCIAL'' AND ENDSWITH(C_CAMPAIGN,''-ORG'') THEN ''Organic''
        
        WHEN "Channel" = ''PAID SEARCH'' AND STARTSWITH(C_CAMPAIGN,''MW_BR_'') THEN ''Brand Search''
        WHEN "Channel" = ''PAID SEARCH'' AND STARTSWITH(C_CAMPAIGN,''MW_NB_'') THEN ''Non-Brand Search''
        WHEN "Channel" = ''PAID SEARCH'' AND STARTSWITH(C_CAMPAIGN,''MADEWELL_SHOPPING_PLA'') THEN ''Shopping Ads''
        WHEN "Channel" = ''PAID SEARCH'' AND CONTAINS(C_CAMPAIGN,''_PLA_'') THEN ''Shopping Ads''
        WHEN "Channel" = ''PAID SEARCH'' AND C_SOURCE IN (''THESKIMM'') AND C_CAMPAIGN !=''MWAFFI00001'' THEN ''Other''
        
        WHEN "Channel" = ''PAID SEARCH'' AND C_SOURCE IN (''THESKIMM'') AND C_CAMPAIGN!=''MWAFFI00001'' THEN ''Other''
        
        WHEN "Channel" = ''PAID SEARCH'' AND C_SOURCE IN (''FACEBOOK'',''TIKTOK'') AND C_CAMPAIGN=''MWAFFI00001'' THEN ''Other''
        
        WHEN "Channel" = ''AFFILIATE'' AND REGEXP_LIKE(C_INITIATIVE,''^LOYALTY$'', ''i'') THEN ''Loyalty''
        WHEN "Channel" = ''AFFILIATE'' AND REGEXP_LIKE(C_INITIATIVE,''^COUPON$'', ''i'') THEN ''Coupon''
        WHEN "Channel" = ''AFFILIATE'' AND (REGEXP_LIKE(C_INITIATIVE,''^BLOGGERS$'') OR REGEXP_LIKE(C_INITIATIVE,''^BLOGGER$'', ''i'') OR REGEXP_LIKE(C_INITIATIVE,''^AMBASSADOR$'', ''i'')) THEN ''Bloggers''
        
        WHEN "Channel" = ''AFFILIATE'' AND (REGEXP_LIKE(C_INITIATIVE,''^MEDIA$'', ''i'') OR REGEXP_LIKE(C_INITIATIVE,''^SHOPPING & CONTENT$'', ''i''))THEN ''Media/Content''
        
        WHEN "Channel" = ''AFFILIATE'' AND REGEXP_LIKE(C_INITIATIVE,''^SHOPPING$'', ''i'') AND C_LASTTOUCHCHANNEL!=''PAID SEARCH'' THEN ''Media/Content''
        
        WHEN "Channel" = ''AFFILIATE'' AND REGEXP_LIKE(C_INITIATIVE,''^CONTENT$'', ''i'') THEN ''Media/Content''
        
        WHEN "Channel" = ''AFFILIATE'' AND C_SOURCE IN (''AFFILIATE'',''DIGIDIP'',''HOWL TECHNOLOGIES, INC.'', ''HOWL+TECHNOLOGIES,+INC.'',''HUE & STRIPE'',''JOANNA GODDARD, INC.'',''JOANNA GODDARD, INC.'', ''KAT GRIFFIN'', ''MAGICLINKS'', ''RSTYLE.ME'',''REWARDSTYLE'', ''SHOP MY SHELF, INC.'', ''SHOP+MY+SHELF,+INC.'',''SHOPLOOK INC.'',''SHOPLOOK'') THEN ''Bloggers''
        
        WHEN "Channel" = ''AFFILIATE'' AND C_SOURCE IN (''A360 MEDIA, LLC'', ''ACTIVE JUNKY, INC.'', ''BRANDCYCLE INC.'',''BRANDCYCLE+INC.'', ''BUSINESS INSIDER'', ''BUZZFEED'', ''BUZZFEED MEDIA ENTERPRISES, INC.'',''BUZZFEED+MEDIA+ENTERPRISES,+INC.'',''BYRDIE.COM'', ''CLIQUE MEDIA, INC. | WHO WHAT WEAR'',''CLIQUE+MEDIA,+INC.++|+WHO+WHAT+WEAR'', ''CNN DIGITAL'', ''CONDÉ NAST'', ''CUPOFJO.COM'', ''DAPPERED'',''DOW JONES & COMPANY, INC.'', ''E! NEWS'',''E! NEWS'',''E!+NEWS'',  ''EFFORTLESSGENT'',''EFFORTLESSGENT'', ''FOOD52, INC.'',''FORBES MEDIA'', ''FORBES.COM'',''FUTURE US, LLC | WHO WHAT WEAR'', ''FUTURE PUBLISHING LIMITED'',''FUTURE PUBLISHING LTD'', ''FUTURE PUBLISHING LTD SAVINGS'', ''GLITTER MAGAZINE | SOEURS MEDIA GROUP'', ''GOODPIX (PIXAVO, INC)'', ''HEARST MAGAZINE MEDIA'',''HEARST+MAGAZINE+MEDIA'',''ID.ME'', ''INSTYLE.COM'', ''INSIDEHOOK'' ,''LEAF GROUP'',''LEAF+GROUP'', ''MAVELY'', ''MOTHERLY'',''MEREDITH CORPORATION'',''MODESENS INC.'',''NEW YORK POST'',''NEW+YORK+POST'',''NYMAG.COM'', ''NBCUNIVERSAL (US)'',''PAUL LARGE'', ''PAUL+LARGE'',''PENSKE MEDIA CORPORATION'', ''POPSUGAR.COM'', ''REVIEWED.COM'', ''RMS PROJECTS LLC'', ''RMS PROJECTS LLC'',''SITEPLUG'', ''SLEEK'', ''SKIMLINKS'', ''SOVRN INC'',''THE ARENA PLATFORM, INC'',''THE+ARENA+PLATFORM,+INC'',''THE DAILY BEAST'', ''TINYBEANS USA LTD'', ''THESKIMM.COM'', ''THESKIMM'', ''WIRECUTTER INC.'',''WIRECUTTER+INC.'',''WILDFIRE SYSTEMS'',''WHAT TO EXPECT'',''WHOWHATWEAR.COM'',''WOW MEDIA PRODUCTS INC.'',''VOX MEDIA'') THEN ''Media/Content''
        
        WHEN "Channel" = ''AFFILIATE'' AND C_SOURCE IN (''AFFIRM'', ''AFFIRM INC.'', ''AFTERPAY US INC'',''AFTERPAY+US+INC,'', ''CC.RETAILMENOT.COM'', ''CHICHIHAHA LIMITED'', ''DEMAND.IO'', ''DEALMOON.COM'', ''FATCOUPON TECHNOLOGY LTD'', ''FATCOUPON+TECHNOLOGY+LTD'',''FORBES COUPONS (UPFEAT MEDIA)'', ''GSG NORTH AMERICA LLC'', ''JOINHONEY.COM'', ''KARMA (FORMERLY SHOPTAGR)'', ''KARMA SHOPPING LTD'', ''KARMA+SHOPPING+LTD'',''KLARNA INC. (U.S.)'',''KLARNA+INC.+(U.S.)'', ''LINKGAINS (HK) LIMITED'',''PRICEPP LLC'', ''REBATESME LLC'', ''RETAILMENOT.COM'', ''SAVINGS UNITED USA'', ''SLICKDEALS LLC'', ''SMTM'', ''WHALESHARK MEDIA: RETAILMENOT.COM'', ''ZIP CO US (PREVIOUSLY QUADPAY)'') THEN ''Coupon''
        
        WHEN "Channel" = ''AFFILIATE'' AND  C_SOURCE IN (''BEFRUGAL.COM'', ''CAPITAL ONE SHOPPING'', ''CARTERA COMMERCE'', ''CARTERA+COMMERCE'',''CASHREWARDS OPERATIONS PTY LTD'', ''COUPONCABIN'', ''EXTRABUX, INC.'', ''FLEXOFFERS.COM, LLC'', ''HAITAO LLC'',''HONEY SCIENCE CORPORATION'',''IBOTTA, INC.'',''INCENTIVE NETWORKS'',''PIGGY, LLC'',''PRODEGE, LLC'',''RAKUTEN.COM'',''TOPCASHBACK LTD'',''TOPCASHBACK (USA) INC'') THEN ''Loyalty''
        
        
        WHEN "Channel" = ''AFFILIATE'' AND CONTAINS(C_SOURCE, ''SHOPSTYLE'') THEN ''Bloggers''
        
        WHEN "Channel" = ''AFFILIATE'' AND CONTAINS(C_SOURCE, ''EBATES'') THEN ''Loyalty''
        
        WHEN "Channel" = ''AFFILIATE'' AND REGEXP_LIKE(C_SOURCE,''LTK'') AND REGEXP_LIKE(C_SOURCE,''AFFILIATE'') THEN ''Bloggers''
        
        WHEN "Channel" = ''AFFILIATE'' AND REGEXP_LIKE(C_SOURCE,''^RSTYLE.ME$'', ''i'') THEN ''Bloggers''
        
        WHEN "Channel" = ''AFFILIATE'' AND REGEXP_LIKE(C_SOURCE,''^SHOPSTYLE'', ''i'') THEN ''Bloggers''
        
        WHEN "Channel" = ''EMAIL'' AND REGEXP_LIKE(C_INITIATIVE,''^SALE$'', ''i'') THEN ''Promo''
        WHEN "Channel" = ''EMAIL'' AND REGEXP_LIKE(C_INITIATIVE,''^PROMO$'', ''i'') THEN ''Promo''
        WHEN "Channel" = ''EMAIL'' AND REGEXP_LIKE(C_INITIATIVE,''^MIX$'', ''i'') THEN ''Mix''
        WHEN "Channel" = ''EMAIL'' AND  REGEXP_LIKE(C_INITIATIVE,''^TRIGGER$'', ''i'') THEN ''Trigger''
        WHEN "Channel" = ''EMAIL'' AND REGEXP_LIKE(C_INITIATIVE,''^TRANSACTIONAL$'', ''i'') THEN ''Transactional''
        WHEN "Channel" = ''EMAIL'' AND REGEXP_LIKE(C_INITIATIVE,''^TRANSACTION$'', ''i'') THEN ''Transactional''
        WHEN "Channel" = ''EMAIL'' AND  REGEXP_LIKE(C_INITIATIVE,''^BAU$'', ''i'') THEN ''Bau''
        WHEN "Channel" = ''EMAIL'' AND REGEXP_LIKE(C_INITIATIVE,''^MARKETING$'', ''i'') THEN ''Marketing''
        WHEN "Channel" = ''EMAIL'' AND  REGEXP_LIKE(C_INITIATIVE,''^BRANDING$'', ''i'') AND C_SOURCE !=''FACEBOOK'' AND C_SOURCE !=''PINTEREST'' THEN ''Branding''
        
        WHEN "Channel" = ''EMAIL'' AND  REGEXP_LIKE(C_INITIATIVE,''^BRANDING$'', ''i'') AND C_SOURCE!=''FACEBOOK'' AND C_SOURCE!=''PINTEREST'' THEN ''Branding''
        
        WHEN "Channel" = ''EMAIL'' THEN ''Other'' 
        
        WHEN "Channel" = ''SMS'' AND REGEXP_LIKE(C_INITIATIVE,''^PROMO$'', ''i'') THEN ''Promo''
        WHEN "Channel" = ''SMS'' AND REGEXP_LIKE(C_INITIATIVE,''^MARKETING$'', ''i'') THEN ''Marketing''
        WHEN "Channel" = ''SMS'' AND REGEXP_LIKE(C_INITIATIVE,''^BRANDING$'', ''i'') THEN ''Branding''
        WHEN "Channel" = ''SMS'' AND  REGEXP_LIKE(C_INITIATIVE,''^TRIGGER$'', ''i'') THEN ''Trigger''
        WHEN "Channel" = ''SMS'' THEN ''Other''
        
        WHEN "Channel" = ''PAID SEARCH'' AND (REGEXP_LIKE(C_INITIATIVE,''^BRAND_SEARCH$'', ''i'') OR REGEXP_LIKE(C_INITIATIVE,''^SEARCH BRAND$'', ''i'') OR REGEXP_LIKE(C_INITIATIVE,''^SEARCH_BRAND$'', ''i'') OR STARTSWITH(C_INITIATIVE,''MW_BR_'')) THEN ''Brand Search''
        
        WHEN  "Channel" = ''PAID SEARCH'' AND (REGEXP_LIKE(C_INITIATIVE,''^NONBRAND_SEARCH$'', ''i'') OR REGEXP_LIKE(C_INITIATIVE,''^SEARCH NONBRAND$'', ''i'') OR REGEXP_LIKE(C_INITIATIVE,''^SEARCH_NONBRAND$'', ''i'')) THEN ''Non-Brand Search''
        
        WHEN "Channel" = ''PAID SEARCH'' AND REGEXP_LIKE(C_INITIATIVE,''^SHOPPING_ADS$'', ''i'') AND C_SOURCE!=''FACEBOOK'' THEN ''Shopping Ads''
        
        WHEN "Channel" = ''PAID SEARCH'' AND (REGEXP_LIKE(C_INITIATIVE,''^SHOPPING ADS NONBRAND$'', ''i'')  OR REGEXP_LIKE(C_INITIATIVE,''^SHOPPING_NONBRAND_SSC$'', ''i'') OR REGEXP_LIKE(C_INITIATIVE,''^SHOPPING_NONBRAND_SSC_MEN$'', ''i'')OR REGEXP_LIKE(C_INITIATIVE,''^SMART SHOPPING$'', ''i'') OR REGEXP_LIKE(C_INITIATIVE ,''^SMART_SHOPPING$'', ''i'') OR REGEXP_LIKE(C_INITIATIVE,''^SHOPPING_NONBRAND_SSC_NCA$'', ''i'') OR REGEXP_LIKE(C_INITIATIVE,''^SHOPPING ADS BRAND$'', ''i'') OR CONTAINS(C_INITIATIVE,''_PLA_'')) THEN ''Shopping Ads''
        
        WHEN "Channel" = ''SOCIAL'' AND REGEXP_LIKE(C_INITIATIVE,''^DYNAMIC$'', ''i'') THEN ''Dynamic''
        WHEN "Channel" = ''SOCIAL'' AND REGEXP_LIKE(C_INITIATIVE,''^PROMO$'', ''i'') THEN ''Promo''
        WHEN "Channel" = ''SOCIAL'' AND REGEXP_LIKE(C_INITIATIVE,''^PRODUCT$'', ''i'') THEN ''Product''
        WHEN "Channel" = ''SOCIAL'' AND CONTAINS(C_INITIATIVE,''ADVANTAGEPLUS'') THEN ''Advantage Plus''
        WHEN "Channel" = ''SOCIAL'' AND CONTAINS(C_INITIATIVE,''ASC'') THEN ''Advantage Plus''
        WHEN "Channel" = ''SOCIAL'' AND REGEXP_LIKE(C_INITIATIVE,''^ORGANIC$'', ''i'') THEN ''Organic''
        WHEN "Channel" = ''SOCIAL'' AND REGEXP_LIKE(C_INITIATIVE,''^SOCIALORGANIC$'', ''i'') THEN ''Organic''
        WHEN "Channel" = ''SOCIAL'' AND REGEXP_LIKE(C_INITIATIVE,''^PARTNERSHIP$'', ''i'') THEN ''Creator''
        WHEN "Channel" = ''SOCIAL'' AND REGEXP_LIKE(C_INITIATIVE,''^CREATOR$'', ''i'') THEN ''Creator''
        WHEN "Channel" = ''SOCIAL'' AND CONTAINS(C_INITIATIVE,''DPA'') THEN ''Dynamic''
        WHEN "Channel" = ''SOCIAL'' AND CONTAINS(C_INITIATIVE,''PRODUCT'') THEN ''Product''
        WHEN "Channel" = ''SOCIAL'' AND CONTAINS(C_INITIATIVE, ''WWW.INSTAGRAM.COM'') THEN ''Organic''
        WHEN "Channel" = ''SOCIAL'' AND CONTAINS(C_INITIATIVE, ''DASHHUDSON'') THEN ''Organic''
        WHEN "Channel" = ''SOCIAL'' THEN ''Other''
        
        WHEN "Channel" = ''REFERRAL'' AND REGEXP_LIKE(C_INITIATIVE,''^FORGOT_PASSWORD$'', ''i'') THEN ''Forgot Password''
        WHEN "Channel"=''REFERRAL'' AND C_CAMPAIGN = ''2024_JC_WEBAPPPASSWORDLESSLOGIN_US_EMSL'' THEN ''Forgot Password''
        WHEN "Channel"=''REFERRAL'' AND REGEXP_LIKE(C_CAMPAIGN, ''^PASSWORD-RESET-EMAIL$'', ''i'') THEN ''Forgot Password''
        WHEN "Channel" = ''REFERRAL'' AND REGEXP_LIKE(C_CAMPAIGN, ''^CHROME-CART$'', ''i'') THEN ''Other''
        WHEN "Channel" = ''REFERRAL'' AND CONTAINS(C_SOURCE,''TALKABLE'') THEN ''Vendor''
        
        WHEN "Channel" = ''REFERRAL'' AND REGEXP_LIKE(C_INITIATIVE,''^VENDOR$'',''i'') THEN ''Vendor''
        
        WHEN "Channel" = ''REFERRAL'' AND REGEXP_LIKE(LOWER(C_INITIATIVE),''TRANSACTIONAL'') THEN ''Forgot Password''
        WHEN "Channel" = ''REFERRAL'' AND C_SOURCE IN (''PORTAL.AFTERPAY.COM'',''APPLEID.APPLE.COM'') THEN ''Alt Payment Methods''
        WHEN "Channel" = ''REFERRAL'' AND C_INITIATIVE IN (''SHIPPINGTRACKING'',''SHIPPINGRETURN'') THEN ''Shipping & Returns''
        WHEN "Channel" = ''REFERRAL'' AND C_CAMPAIGN =''(NOT SET)'' AND C_SOURCE =''REFERRAL'' THEN ''Other''
        WHEN "Channel" = ''REFERRAL'' THEN ''Other''
        ELSE ''Other''
        END AS "Initiative",
        coalesce(C_INITIATIVE, '''') AS "Source Initiative",
        COALESCE(C_CAMPAIGN, '''') AS C_CAMPAIGN
        FROM
        ALL_CHANNEL TS
),

GET_NEW_RECORD AS(
    SELECT
    "Source",
    "Channel",
    "Channel Type",
    "Channel Sub Type",
    "Initiative",
    "Source Initiative",
    C_CAMPAIGN
    FROM
    TRANSFORMED_DATA
    
    EXCEPT
    
    SELECT
    "Source",
    "Channel",
    "Channel Type",
    "Channel Sub Type",
    "Initiative",
    "Source Initiative",
    C_CAMPAIGN
    FROM
    RPT."GA CHANNEL"
),

GET_MAX_ID AS 
(
    SELECT COALESCE(MAX("ID"), 0) AS MAX_ID
    FROM
    RPT."GA CHANNEL"
)

SELECT
"Source",
"Channel",
"Channel Type",
"Channel Sub Type",
"Initiative",
"Source Initiative",
C_CAMPAIGN,
RANK() OVER(ORDER BY "Source", "Channel", "Channel Type", "Channel Sub Type", "Initiative", "Source Initiative", C_CAMPAIGN) + (SELECT MAX_ID FROM GET_MAX_ID) AS ID
FROM
GET_NEW_RECORD;



-- Return success message
    RETURN ''Table RPT."GA CHANNEL" created or replaced successfully.'';

END
';