CREATE OR REPLACE PROCEDURE "USP_POPULATE_PASSPORT_CUSTOMER"()
RETURNS VARCHAR(100)
LANGUAGE SQL
EXECUTE AS OWNER
AS '
BEGIN
    CREATE OR REPLACE TABLE Temp."PASSPORT CUSTOMER" (
        MASTERCUSTOMERID VARCHAR(16777216),
        "Customer Id" NUMBER(10, 0),
        C_PLCCFLAG NUMBER(3, 0),
        C_PLCCSIGNUPDATE NUMBER(18, 0),
        C_PLCCCLOSEDATE NUMBER(18, 0),
        C_COBRANDFLAG NUMBER(3, 0),
        C_COBRANDSIGNUPDATE NUMBER(18, 0),
        C_COBRANDCLOSEDATE NUMBER(18, 0)
    );

    INSERT INTO Temp."PASSPORT CUSTOMER" (
        MASTERCUSTOMERID,
        "Customer Id",
        C_PLCCFLAG,
        C_PLCCSIGNUPDATE,
        C_PLCCCLOSEDATE,
        C_COBRANDFLAG,
        C_COBRANDSIGNUPDATE,
        C_COBRANDCLOSEDATE
    )
    WITH ALL_CUSTOMERS AS (
        SELECT
            DISTINCT
            MASTERCUSTOMERID,
            CASE WHEN C_PLCCFLAG = ''Y'' THEN 1 ELSE 0 END AS C_PLCCFLAG,
            TO_NUMBER(TO_CHAR(C_PLCCSIGNUPDATE, ''YYYYMMDD'')) AS C_PLCCSIGNUPDATE,
            TO_NUMBER(TO_CHAR(C_PLCCCLOSEDATE, ''YYYYMMDD'')) AS C_PLCCCLOSEDATE,
            CASE WHEN C_COBRANDFLAG = ''Y'' THEN 1 ELSE 0 END AS C_COBRANDFLAG,
            TO_NUMBER(TO_CHAR(C_COBRANDSIGNUPDATE, ''YYYYMMDD'')) AS C_COBRANDSIGNUPDATE,
            TO_NUMBER(TO_CHAR(C_COBRANDCLOSEDATE, ''YYYYMMDD'')) AS C_COBRANDCLOSEDATE
        FROM
            CDP_JC.PUBLIC.CUSTOMERSUMMARY
    )
    SELECT 
        MASTERCUSTOMERID,
        DENSE_RANK() OVER (ORDER BY MASTERCUSTOMERID DESC) AS "Customer Id",
        C_PLCCFLAG,
        C_PLCCSIGNUPDATE,
        CASE WHEN C_PLCCFLAG = 1 AND (C_PLCCCLOSEDATE IS NULL OR C_PLCCCLOSEDATE IN (99990101, 19000101)) THEN TO_CHAR(CURRENT_DATE(), ''YYYYMMDD'')::INTEGER ELSE C_PLCCCLOSEDATE::INTEGER END AS C_PLCCCLOSEDATE,
        C_COBRANDFLAG,
        C_COBRANDSIGNUPDATE,
        CASE WHEN C_COBRANDFLAG = 1 AND (C_COBRANDCLOSEDATE IS NULL OR C_COBRANDCLOSEDATE IN (99990101, 19000101)) THEN TO_CHAR(CURRENT_DATE(), ''YYYYMMDD'')::INTEGER ELSE C_COBRANDCLOSEDATE::INTEGER END AS C_COBRANDCLOSEDATE
    FROM 
        ALL_CUSTOMERS;

    DROP TABLE IF EXISTS RPT."PASSPORT CUSTOMER";  -- Added IF EXISTS to avoid errors if the table does not exist.
    ALTER TABLE 
        Temp."PASSPORT CUSTOMER" 
    RENAME TO RPT."PASSPORT CUSTOMER";

    -- Return success message
    RETURN ''Table RPT."PASSPORT CUSTOMER" created or replaced successfully.'';
END;
';