create or replace view VW_CUSTOM_ROWHEADER_FULLPRICECUSTOMR_YOY(
	"Row Header",
	"Row Sort",
	"Year"
) as
WITH CUSTOM_COLUMN AS(
    SELECT 'New' AS "Row Header", 1 AS "Row Sort"
    UNION ALL
    SELECT 'Retained', 2
    UNION ALL
    SELECT 'Stores' AS "Row Header", 3 AS "Row Sort"
    UNION ALL
    SELECT 'Ecomm', 4
    UNION ALL
    SELECT 'Total', 5
    UNION ALL
    SELECT '$/Stores Customer', 6
    UNION ALL
    SELECT '$/Ecomm Customer', 7
    UNION ALL
    SELECT '$/Customer', 8
),
GET_LAST_TWO_FISCAL_YEARS AS(
    SELECT MAX(FISCALYEAR) AS "Year" FROM  CDP_JC.PUBLIC.TRANSACTIONSUMMARY T
    LEFT JOIN CDP_JC.PUBLIC.TIMESUMMARY TS ON DATE(T.TransactionDate) = DATE(TS.DATEINUNIX)
    UNION ALL
    SELECT MAX(FISCALYEAR) - 1 FROM  CDP_JC.PUBLIC.TRANSACTIONSUMMARY T
    LEFT JOIN CDP_JC.PUBLIC.TIMESUMMARY TS ON DATE(T.TransactionDate) = DATE(TS.DATEINUNIX)
)
SELECT "Row Header", "Row Sort", "Year" FROM CUSTOM_COLUMN JOIN GET_LAST_TWO_FISCAL_YEARS;