create or replace view VW_COMPLETED_YEAR_WEEK(
	"Id"
) as
WITH COMPLETEDFISCALYEAR AS
(
    SELECT
    MAX("Fiscal Year") AS FISCALYEAR
    FROM
    EDW_MARKETING_PRD.RPT.DATE
    WHERE "Completed Week Flag" = 1
),

COMPLETEDFISCALWEEK AS
(
    SELECT
    MAX("Fiscal Week") AS FISCALWEEK
    FROM
    EDW_MARKETING_PRD.RPT.DATE 
    WHERE "Completed Week Flag" = 1
    AND "Fiscal Year" IN (SELECT FISCALYEAR FROM COMPLETEDFISCALYEAR)
)

SELECT
"Id"
FROM
EDW_MARKETING_PRD.RPT.DATE WHERE "Fiscal Year" IN (SELECT FISCALYEAR FROM COMPLETEDFISCALYEAR)
AND "Fiscal Week" IN (SELECT FISCALWEEK FROM COMPLETEDFISCALWEEK);