create or replace view VW_MKT_TRANSACTIONSUMMARY_TEST_LOYALTY(
	"MasterCustomerId",
	"FM Status Type",
	"FQ Status Type",
	"FY Status Type",
	"Organization Id",
	"Transaction Date Id",
	"Buyer Identification",
	"Sub Type",
	"Product Id",
	"Price Type",
	"Channel",
	"Channel Type",
	"Channel SubType",
	"Loyalty Tier Stage",
	"Loyalty Flag",
	"Loyalty Tier",
	"Sale Revenue",
	"Sale Margin"
) as 

SELECT
T.MASTERCUSTOMERID AS "MasterCustomerId"
,C_STATUSTYPEFM AS "FM Status Type"
,C_STATUSTYPEFQ AS "FQ Status Type"
,C_STATUSTYPEFY AS "FY Status Type"
,VO."Id" AS "Organization Id"
,ts.id  AS "Transaction Date Id"
,BUYERIDENTIFICATION AS "Buyer Identification"
,T.SUBTYPE AS "Sub Type"
,PO."Id" AS "Product Id"
,C_FPMDITEM AS "Price Type"
,case when T.c_devicetype='APP' then 'APP'
     when T.c_lasttouchchannel in ('AFFILIATE','AFFILIATES') then 'AFFILIATES'
     when T.c_lasttouchchannel in ('NATURAL SEARCH','ORGANIC SEARCH','ORGANIC') then 'SEO'
     when T.c_lasttouchchannel in ('VENDOR','REFERRAL') then 'REFERRAL'
     when T.c_lasttouchchannel in ('MBL DTS','WEB DTS','DIRECT') then 'DIRECT'
     when T.c_lasttouchchannel in ('APP DTS') then 'APP'
     when T.c_lasttouchchannel in ('INTERNAL','OTHER','(OTHER)','MISC') then 'OC NOT CAPTURED'
     else T.c_lasttouchchannel end as Channel
,case when channel in ('EMAIL','SMS','DIRECT','REFERRAL','SEO','APP','CUSTOMER SERVICE CHANNEL','OC NOT CAPTURED') THEN 'UNPAID'
     when channel in ('AFFILIATES','PAID SEARCH','SOCIAL','DISPLAY') THEN 'PAID'
     else channel end as "Channel Type"
,case when channel in ('EMAIL','SMS') then 'EMAIL + SMS'
     when channel in ('DIRECT','REFERRAL','SEO') then 'ORGANIC CHANNELS'
     when channel in ('CUSTOMER SERVICE CHANNEL','OC NOT CAPTURED') then 'OTHER' 
     else channel end as "Channel SubType"
,COALESCE(R.TIER, T.C_LOYALTYTIER, C.C_LOYALTYTIER) AS "Loyalty Tier Stage"
,CASE 
     WHEN "Loyalty Tier Stage" IS NOT NULL THEN 'Loyalty'
     ELSE 'Non-Loyalty' END AS "Loyalty Flag"
,COALESCE("Loyalty Tier Stage", 'Non-Loyalty') AS "Loyalty Tier"
,SUM(SALEREVENUE) AS "Sale Revenue"
,SUM(SALEREVENUE - COSTBASIS) AS "Sale Margin"
FROM CDP.PUBLIC.TRANSACTIONSUMMARY T
LEFT JOIN CDP.PUBLIC.CUSTOMERSUMMARY C ON T.MASTERCUSTOMERID = C.MASTERCUSTOMERID
LEFT JOIN CDP.PUBLIC.TIMESUMMARY TS ON TO_DATE(TS.DATEINUNIX) = TO_DATE(t.TRANSACTIONTIMESTAMP)
LEFT JOIN CDP.PUBLIC.ORGANIZATIONSUMMARY O ON O.ID = T.ORGANIZATIONID
LEFT JOIN VW_MKT_ORGANIZATIONSUMMARY VO ON VO."Brand Name" = O.LEVEL1NAME AND VO."Type" = O.TYPE
LEFT JOIN CDP.PUBLIC.PRODUCTCATEGORYXREF PX ON PX.PRODUCTID = T.PRODUCTID
LEFT JOIN  CDP.PUBLIC.PRODUCTCATEGORYSUMMARY PS ON PS.Id = PX.PRODUCTCATEGORYID
LEFT JOIN VW_MKT_PRODUCTSUMMARY PO ON PO."Product Category Level 1" = PS.LEVEL1NAME
LEFT JOIN 
    (--ONLY GET DISTINCT TRANSACTIONID. IF YOU USE THE WHOLE TABLE, WHERE MULTIPLE REWARDS ARE USED IN THE SAME TRANSACTION, YOU CAN GET A CARTESIAN PRODUCT AND OVER-INFLATE THE AGGREGATE MEASURES
      SELECT DISTINCT TIER, TRANSACTIONID FROM LOYALTY.JC_PRD.T_LOY_TRANS_REWARDS WHERE REWARDS IS NOT NULL
    ) R
    ON R.TRANSACTIONID = T.TRANSACTIONID
WHERE TO_DATE(TRANSACTIONTIMESTAMP) >= (SELECT TO_DATE(DATEINUNIX) FROM CDP.PUBLIC.TIMESUMMARY WHERE FISCALYEAR = (SELECT FISCALYEAR FROM CDP.PUBLIC.TIMESUMMARY WHERE TO_DATE(DATEINUNIX) > current_date-7 AND TO_DATE(DATEINUNIX) <= current_date AND FISCALDAYOFWEEK = 7)-1 AND FISCALDAYOFMONTH = 1 AND FISCALMONTH = 1)
AND BUYERIDENTIFICATION = 'Identified' AND T.SUBTYPE in ('Demand', 'Shipped')
GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16

UNION ALL

SELECT
T.MASTERCUSTOMERID
,C_STATUSTYPEBRANDFM AS "FM Status Type"
,C_STATUSTYPEBRANDFQ AS "FQ Status Type"
,C_STATUSTYPEBRANDFY AS "FY Status Type"
,VO."Id" AS "Organization Id"
,ts.id AS "Transaction Date Id"
,BUYERIDENTIFICATION AS "Buyer Identification"
,T.SUBTYPE AS "Sub Type"
,PO."Id" AS "Product Id"
,C_FPMDITEM AS "Price Type"
,case when T.c_devicetype='APP' then 'APP'
     when T.c_lasttouchchannel in ('AFFILIATE','AFFILIATES') then 'AFFILIATES'
     when T.c_lasttouchchannel in ('NATURAL SEARCH','ORGANIC SEARCH','ORGANIC') then 'SEO'
     when T.c_lasttouchchannel in ('VENDOR','REFERRAL') then 'REFERRAL'
     when T.c_lasttouchchannel in ('MBL DTS','WEB DTS','DIRECT') then 'DIRECT'
     when T.c_lasttouchchannel in ('APP DTS') then 'APP'
     when T.c_lasttouchchannel in ('INTERNAL','OTHER','(OTHER)','MISC') then 'OC NOT CAPTURED'
     else T.c_lasttouchchannel end as Channel
,case when channel in ('EMAIL','SMS','DIRECT','REFERRAL','SEO','APP','CUSTOMER SERVICE CHANNEL','OC NOT CAPTURED') THEN 'UNPAID'
     when channel in ('AFFILIATES','PAID SEARCH','SOCIAL','DISPLAY') THEN 'PAID'
     else channel end as "Channel Type"
,case when channel in ('EMAIL','SMS') then 'EMAIL + SMS'
     when channel in ('DIRECT','REFERRAL','SEO') then 'ORGANIC CHANNELS'
     when channel in ('CUSTOMER SERVICE CHANNEL','OC NOT CAPTURED') then 'OTHER' 
     else channel end as "Channel SubType"
,COALESCE(R.TIER, T.C_LOYALTYTIER, C.C_LOYALTYTIER) AS "Loyalty Tier Stage"
,CASE 
     WHEN "Loyalty Tier Stage" IS NOT NULL THEN 'Loyalty'
     ELSE 'Non-Loyalty' END AS "Loyalty Flag"
,COALESCE("Loyalty Tier Stage", 'Non-Loyalty') AS "Loyalty Tier"
,SUM(SALEREVENUE) AS "Sale Revenue"
,SUM(SALEREVENUE - COSTBASIS) AS "Sale Margin"
FROM CDP_JC.PUBLIC.TRANSACTIONSUMMARY T
LEFT JOIN CDP_JC.PUBLIC.CUSTOMERSUMMARY C ON T.MASTERCUSTOMERID = C.MASTERCUSTOMERID
LEFT JOIN CDP_JC.PUBLIC.TIMESUMMARY TS ON TO_DATE(TS.DATEINUNIX) = TO_DATE(t.TRANSACTIONTIMESTAMP)
LEFT JOIN CDP_JC.PUBLIC.ORGANIZATIONSUMMARY O ON O.ID = T.ORGANIZATIONID
LEFT JOIN VW_MKT_ORGANIZATIONSUMMARY VO ON VO."Brand Name" = O.LEVEL1NAME AND VO."Type" = O.TYPE
LEFT JOIN CDP_JC.PUBLIC.PRODUCTCATEGORYXREF PX ON PX.PRODUCTID = T.PRODUCTID
LEFT JOIN  CDP_JC.PUBLIC.PRODUCTCATEGORYSUMMARY PS ON PS.Id = PX.PRODUCTCATEGORYID
LEFT JOIN VW_MKT_PRODUCTSUMMARY PO ON PO."Product Category Level 1" = PS.LEVEL1NAME
LEFT JOIN 
    (--ONLY GET DISTINCT TRANSACTIONID. IF YOU USE THE WHOLE TABLE, WHERE MULTIPLE REWARDS ARE USED IN THE SAME TRANSACTION, YOU CAN GET A CARTESIAN PRODUCT AND OVER-INFLATE THE AGGREGATE MEASURES
      SELECT DISTINCT TIER, TRANSACTIONID FROM LOYALTY.JC_PRD.T_LOY_TRANS_REWARDS WHERE REWARDS IS NOT NULL
    ) R
    ON R.TRANSACTIONID = T.TRANSACTIONID
WHERE TO_DATE(TRANSACTIONTIMESTAMP) >= (SELECT TO_DATE(DATEINUNIX) FROM CDP.PUBLIC.TIMESUMMARY WHERE FISCALYEAR = (SELECT FISCALYEAR FROM CDP.PUBLIC.TIMESUMMARY WHERE TO_DATE(DATEINUNIX) > current_date-7 AND TO_DATE(DATEINUNIX) <= current_date AND FISCALDAYOFWEEK = 7)-1 AND FISCALDAYOFMONTH = 1 AND FISCALMONTH = 1)
AND BUYERIDENTIFICATION = 'Identified' AND T.SUBTYPE in ('Demand', 'Shipped')
GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16;