create or replace view VW_PASSPORT_LOYALTY_NRF(
	"Loyalty Tier",
	"Customer Loyalty Flag",
	"Date Key",
	"Channel Flag",
	"Brand ID",
	"MasterCustomer ID",
	"Reward Flag",
	"Sub Type",
	"Status Type",
	"FM Status Type",
	"FQ Status Type",
	"FY Status Type",
	"Loyalty Signup Date Id",
	"Loyalty SignUp Channel",
	"Cashier Associate",
	"Email Capture Flag",
	"Employee Flag",
	"Net Revenue",
	"Net Units",
	"Net Cost Basis",
	"DMD Revenue",
	"DMD Units",
	"DMD Cost Basis",
	"DMD Transactions",
	"Loyalty Tier Week",
	"Loyalty Tier Month",
	"Loyalty Tier Quarter",
	"Loyalty Tier Year",
	"Loyalty Tier LY Same"
) as
SELECT * FROM RPT."PASSPORT LOYALTY NRF";