create or replace view VW_PASSPORT_MARKETING(
	"MasterCustomerId",
	"Loyalty Key",
	"FM Status Type",
	"FQ Status Type",
	"FY Status Type",
	"Promo Id",
	"Status Type",
	"FM Status Type JCG",
	"FQ Status Type JCG",
	"FY Status Type JCG",
	"Status Type JCG",
	"Organization Id",
	"Transaction Date Id",
	"Loyalty Signup Date Id",
	"Product Id",
	"Price Type",
	"Channel Key",
	"Product Summary Id",
	"JCCC Flag",
	"Transaction Id",
	"Units",
	"Sale Revenue",
	MARGIN,
	"Gross Margin",
	"Promo Sale Revenue",
	"Promo Units",
	"Promo Margin",
	"Promo Gross Margin"
) as
SELECT
"MasterCustomerId",
"Loyalty Key",
"FM Status Type",
"FQ Status Type",
"FY Status Type",
"Promo Id",
"Status Type",
"FM Status Type JCG",
"FQ Status Type JCG",
"FY Status Type JCG",
"Status Type JCG",
"Organization Id",
"Transaction Date Id",
"Loyalty Signup Date Id",
"Product Id",
"Price Type",
"Channel Key",
"Product Summary Id",
"JCCC Flag",
"Transaction Id",
"Units",
"Sale Revenue",
MARGIN,
"Gross Margin",
"Promo Sale Revenue",
"Promo Units",
"Promo Margin",
"Promo Gross Margin"
FROM
EDW_MARKETING_PRD.RPT."PASSPORT MARKETING";