create or replace view VW_PASSPORT_CUSTOMER(
	"Customer Id",
	C_PLCCFLAG,
	C_PLCCSIGNUPDATE,
	C_PLCCCLOSEDATE,
	C_COBRANDFLAG,
	C_COBRANDSIGNUPDATE,
	C_COBRANDCLOSEDATE
) as
SELECT
"Customer Id",
C_PLCCFLAG,
C_PLCCSIGNUPDATE,
C_PLCCCLOSEDATE,
C_COBRANDFLAG,
C_COBRANDSIGNUPDATE,
C_COBRANDCLOSEDATE
FROM
RPT."PASSPORT CUSTOMER"
WHERE 
C_PLCCFLAG = 1 OR C_COBRANDFLAG = 1;