create or replace view VW_PASSPORT_MARKETING_LOYALTY(
	"Loyalty Key",
	"Loyalty Tier Week Status",
	"Feb Loyalty Tier Year Status",
	"March Loyalty Tier Year Status",
	"April Loyalty Tier Year Status",
	"May Loyalty Tier Year Status",
	"June Loyalty Tier Year Status",
	"July Loyalty Tier Year Status",
	"August Loyalty Tier Year Status",
	"September Loyalty Tier Year Status",
	"October Loyalty Tier Year Status",
	"November Loyalty Tier Year Status",
	"December Loyalty Tier Year Status",
	"Jan Loyalty Tier Year Status",
	"Curr Loyalty Tier Year Status",
	"Feb Prev Loyalty Tier Year Status",
	"March Prev Loyalty Tier Year Status",
	"April Prev Loyalty Tier Year Status",
	"May Prev Loyalty Tier Year Status",
	"June Prev Loyalty Tier Year Status",
	"July Prev Loyalty Tier Year Status",
	"August Prev Loyalty Tier Year Status",
	"September Prev Loyalty Tier Year Status",
	"October Prev Loyalty Tier Year Status",
	"November Prev Loyalty Tier Year Status",
	"December Prev Loyalty Tier Year Status",
	"Jan Prev Loyalty Tier Year Status",
	"Curr Prev Loyalty Tier Year Status"
) as
SELECT
"Loyalty Key",
"Loyalty Tier Week Status",
"Feb Loyalty Tier Year Status",
"March Loyalty Tier Year Status",
"April Loyalty Tier Year Status",
"May Loyalty Tier Year Status",
"June Loyalty Tier Year Status",
"July Loyalty Tier Year Status",
"August Loyalty Tier Year Status",
"September Loyalty Tier Year Status",
"October Loyalty Tier Year Status",
"November Loyalty Tier Year Status",
"December Loyalty Tier Year Status",
"Jan Loyalty Tier Year Status",
"Curr Loyalty Tier Year Status",
"Feb Prev Loyalty Tier Year Status",
"March Prev Loyalty Tier Year Status",
"April Prev Loyalty Tier Year Status",
"May Prev Loyalty Tier Year Status",
"June Prev Loyalty Tier Year Status",
"July Prev Loyalty Tier Year Status",
"August Prev Loyalty Tier Year Status",
"September Prev Loyalty Tier Year Status",
"October Prev Loyalty Tier Year Status",
"November Prev Loyalty Tier Year Status",
"December Prev Loyalty Tier Year Status",
"Jan Prev Loyalty Tier Year Status",
"Curr Prev Loyalty Tier Year Status"
FROM RPT."PASSPORT MARKETING LOYALTY";