create or replace TABLE "COUPON VALIDATION KPI" (
	BRAND VARCHAR(8),
	DATE NUMBER(38,0),
	REWARD_ISSUED NUMBER(18,0),
	REWARD_REDEEMED NUMBER(18,0),
	TRANS_COUNT NUMBER(18,0),
	UNITS NUMBER(38,0),
	DMD FLOAT,
	DMD_C FLOAT
);