create or replace TABLE "MADEWELL LOYALTY STATUS NRF" (
	"Loyalty Tier" NUMBER(4,0),
	"Customer Loyalty Flag" VARCHAR(100),
	"Channel Flag" VARCHAR(100),
	"Date Key" NUMBER(38,0),
	"Brand ID" VARCHAR(100),
	"MasterCustomer ID" NUMBER(38,0),
	"Reward Flag" VARCHAR(100),
	"Sub Type" VARCHAR(100),
	"Status Type" NUMBER(5,0),
	"FM Status Type" NUMBER(5,0),
	"FQ Status Type" NUMBER(5,0),
	"FY Status Type" NUMBER(5,0),
	"Loyalty Signup Date Id" NUMBER(38,0),
	"Loyalty SignUp Channel" VARCHAR(200),
	"Cashier Associate" VARCHAR(200),
	"Email Capture Flag" VARCHAR(200),
	"Employee Flag" NUMBER(3,0),
	"Net Revenue" FLOAT,
	"Net Units" FLOAT,
	"Net Cost Basis" FLOAT,
	"DMD Revenue" FLOAT,
	"DMD Units" FLOAT,
	"DMD Cost Basis" FLOAT,
	"DMD Transactions" VARCHAR(200),
	"Loyalty Tier Week" NUMBER(4,0),
	"Loyalty Tier Month" NUMBER(4,0),
	"Loyalty Tier Quarter" NUMBER(4,0),
	"Loyalty Tier Year" NUMBER(4,0),
	"Loyalty Tier LY Same" NUMBER(4,0)
);