create or replace TABLE "MADEWELL MARKETING NRF LOYALTY" (
	"Loyalty Key" NUMBER(38,0),
	"Transaction Date" NUMBER(38,0),
	"Loyalty Tier Week Status" NUMBER(38,0),
	"Feb Loyalty Tier Year Status" NUMBER(38,0),
	"March Loyalty Tier Year Status" NUMBER(38,0),
	"April Loyalty Tier Year Status" NUMBER(38,0),
	"May Loyalty Tier Year Status" NUMBER(38,0),
	"June Loyalty Tier Year Status" NUMBER(38,0),
	"July Loyalty Tier Year Status" NUMBER(38,0),
	"August Loyalty Tier Year Status" NUMBER(38,0),
	"September Loyalty Tier Year Status" NUMBER(38,0),
	"October Loyalty Tier Year Status" NUMBER(38,0),
	"November Loyalty Tier Year Status" NUMBER(38,0),
	"December Loyalty Tier Year Status" NUMBER(38,0),
	"Jan Loyalty Tier Year Status" NUMBER(38,0),
	"Curr Loyalty Tier Year Status" NUMBER(38,0),
	"Feb Prev Loyalty Tier Year Status" NUMBER(38,0),
	"March Prev Loyalty Tier Year Status" NUMBER(38,0),
	"April Prev Loyalty Tier Year Status" NUMBER(38,0),
	"May Prev Loyalty Tier Year Status" NUMBER(38,0),
	"June Prev Loyalty Tier Year Status" NUMBER(38,0),
	"July Prev Loyalty Tier Year Status" NUMBER(38,0),
	"August Prev Loyalty Tier Year Status" NUMBER(38,0),
	"September Prev Loyalty Tier Year Status" NUMBER(38,0),
	"October Prev Loyalty Tier Year Status" NUMBER(38,0),
	"November Prev Loyalty Tier Year Status" NUMBER(38,0),
	"December Prev Loyalty Tier Year Status" NUMBER(38,0),
	"Jan Prev Loyalty Tier Year Status" NUMBER(38,0),
	"Curr Prev Loyalty Tier Year Status" NUMBER(38,0),
	"Last Modified Date" TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);