create or replace TABLE "MADEWELL COUPON STATS AND USAGE" (
	"Issue Date Id" NUMBER(38,0),
	"Brand" VARCHAR(10),
	"Redemption Brand" VARCHAR(10),
	"Loyalty Tier" VARCHAR(100),
	"Brand Sort" NUMBER(38,0),
	"Code" VARCHAR(200),
	"Reward Name" VARCHAR(200),
	"Status" VARCHAR(10),
	"Loyalty Coupon Id" NUMBER(38,0),
	"Expiration Date Id" NUMBER(38,0),
	"Used Date Id" NUMBER(38,0),
	"Transaction Date Id" NUMBER(38,0),
	"Employee Flag" NUMBER(3,0),
	"Organization Id" VARCHAR(20),
	"Days to Usage" NUMBER(38,0),
	"Distribution Channel" VARCHAR(16777216),
	"Status Type" NUMBER(4,0),
	"DMD Revenue" FLOAT,
	"DMD Units" NUMBER(38,0),
	"DMD Cost Basis" FLOAT,
	"Rewards Amount" FLOAT,
	"Transactions" VARCHAR(200)
);