create or replace TABLE "PASSPORT MARKETING" (
	"MasterCustomerId" NUMBER(8,0),
	"Loyalty Key" NUMBER(38,0),
	"FM Status Type" NUMBER(3,0),
	"FQ Status Type" NUMBER(3,0),
	"FY Status Type" NUMBER(3,0),
	"Promo Id" NUMBER(38,0),
	"Status Type" NUMBER(3,0),
	"FM Status Type JCG" NUMBER(3,0),
	"FQ Status Type JCG" NUMBER(3,0),
	"FY Status Type JCG" NUMBER(3,0),
	"Status Type JCG" NUMBER(3,0),
	"Organization Id" NUMBER(5,0),
	"Transaction Date Id" NUMBER(38,0),
	"Loyalty Signup Date Id" NUMBER(38,0),
	"Product Id" NUMBER(38,0),
	"Price Type" NUMBER(38,0),
	"Channel Key" NUMBER(38,0),
	"Product Summary Id" NUMBER(38,0),
	"JCCC Flag" NUMBER(38,0),
	"Transaction Id" NUMBER(20,0),
	"Units" FLOAT,
	"Sale Revenue" FLOAT,
	MARGIN FLOAT,
	"Gross Margin" FLOAT,
	"Promo Sale Revenue" FLOAT,
	"Promo Units" FLOAT,
	"Promo Margin" FLOAT,
	"Promo Gross Margin" FLOAT,
	"Last Modified Date" TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);