create or replace TABLE "PASSPORT COUPON STATS AND USAGE" (
	MCID VARCHAR(100),
	"Issue Date Id" NUMBER(38,0),
	"Brand" VARCHAR(10),
	"Redemption Brand" VARCHAR(10),
	"Loyalty Tier" VARCHAR(100),
	"Brand Sort" NUMBER(38,0),
	"Code" VARCHAR(200),
	"Reward Name" VARCHAR(200),
	"Status" VARCHAR(10),
	"Loyalty Coupon Id" NUMBER(38,0),
	"Expiration Date Id" NUMBER(38,0),
	"Used Date Id" NUMBER(38,0),
	"Transaction Date Id" NUMBER(38,0),
	"Organization ID" VARCHAR(30),
	"Employee Flag" NUMBER(3,0),
	"Days to Usage" NUMBER(38,0),
	"Distribution Channel" VARCHAR(16777216),
	"Status Type" NUMBER(3,0),
	"DMD Revenue" FLOAT,
	"DMD Units" NUMBER(38,0),
	"DMD Cost Basis" FLOAT,
	"Rewards Amount" FLOAT,
	"Transactions" VARCHAR(200),
	"JCCC Tender" VARCHAR(5),
	"JCCC Cardholder" VARCHAR(5),
	"JCCC Customers / Cardholders filter" VARCHAR(5)
);