create or replace TABLE "PASSPORT CUSTOMER" (
	MASTERCUSTOMERID VARCHAR(16777216),
	"Customer Id" NUMBER(10,0),
	C_PLCCFLAG NUMBER(3,0),
	C_PLCCSIGNUPDATE NUMBER(18,0),
	C_PLCCCLOSEDATE NUMBER(18,0),
	C_COBRANDFLAG NUMBER(3,0),
	C_COBRANDSIGNUPDATE NUMBER(18,0),
	C_COBRANDCLOSEDATE NUMBER(18,0)
);