CREATE OR REPLACE TASK "TASK_MID"
  WAREHOUSE = COMPUTE_WH
  SCHEDULE = NULL
  AFTER "01_TASK_ROOT"
AS
  -- Mid-level task depending on root task
  INSERT INTO XFRM.MY_TABLE_MID (id, val) VALUES (2, 'mid');
