name: snowflake-devops-demo

on:
  push:
    branches:
      - PROD
  pull_request:
    branches:
      - PROD
  workflow_dispatch:   # Manual trigger bhi available hoga

jobs:
  deploy-snowflake-changes-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install snowflake-connector-python

      - name: Check if PR exists
        run: |
          PR_URL=$(gh pr list --base PROD --head DEV --state open --json url -q ".[].url")
          if [ -n "$PR_URL" ]; then
            echo "PR exists. Proceeding with deployment"
          else
            echo "No open PR found, skipping deployment."
            exit 0  # Skip deployment if no PR
          fi

      - name: Deploy SQL files, Archive, and Clean up
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
          SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
        run: |
          python deploy_sql_files.py  # Deploy + archive + cleanup

      - name: Commit & Push changes
        env:
          TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}
          git add .
          git commit -m "Auto deploy, archive old versions, and clean up archive" || echo "No changes"
          git push

  close-pr-after-deploy:
    needs: deploy-snowflake-changes-job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Close the PR after successful deployment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_URL=$(gh pr list --base PROD --head DEV --state open --json url -q ".[].url")
          if [ -n "$PR_URL" ]; then
            echo "PR exists. Closing PR: $PR_URL"
            gh pr close "$PR_URL"
          else
            echo "No open PR found"
          fi
