name: snowflake-devops-demo

on:
  push:
    branches:
      - PROD
    paths:
      - 'dbscripts2/**'

  workflow_dispatch:

jobs:
  deploy-snowflake-changes-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Deploy custom SQL files to Snowflake
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
          SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
        run: |
          pip install snowflake-connector-python
          python deploy_sql_files.py

      # Archive old versions of updated files (files that were changed)
      - name: Archive old versions of updated files
        run: python archive_old_versions.py

      # Clean up the archive folder by deleting files older than 7 days
      - name: Clean up archived files older than 7 days
        run: python cleanup_archive.py

      # Commit & push changes if there are any new archived or cleaned files
      - name: Commit & Push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Auto archive old versions and clean up archive" || echo "No changes"
          git push
