name: Deploy Snowflake Changes

on:
  push:
    branches:
      - DEV
      - PROD
    paths:
      - 'dbscripts2/**'

jobs:
  create-pr:
    if: github.ref == 'refs/heads/DEV'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up GitHub Token
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "github-actions"

          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d '{"title":"Automated PR from DEV to PROD","head":"DEV","base":"PROD"}' \
            "https://api.github.com/repos/${{ github.repository }}/pulls"

  deploy-snowflake:
    if: github.ref == 'refs/heads/PROD'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install snowflake-connector-python

      - name: Deploy to Snowflake
        run: |
          python deploy_sql_files.py

      - name: Commit & Push changes
        env:
          TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}
          git add .
          git commit -m "Auto deploy, archive old versions, and clean up archive" || echo "No changes"
          git push

